name: Travis integrator RSVP
language: node_js
node_js:
  - 10
on:
  push:
    branches:
      - master

#before_install:

# command to install dependencies
install:
  - npm ci

# command to run tests
script:
  - npm test